services:
  database:
    build: ./database
    image: leaderboard-database
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres-admin-password"
      POSTGRES_DB: "leaderboard"
  api:
    build: ./api
    image: leaderboard-api
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    ports:
      - 9090:9090
    environment:
      DB_CONNECTION: "host=database port=5432 user=postgres password=postgres-admin-password dbname=leaderboard sslmode=disable connect_timeout=10"
  frontend:
    build: ./frontend
    image: leaderboard-frontend
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    ports:
      - 8080:80

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16